import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionContext from "@/context/SessionContext";
import Navbar from "@/components/ui/Navbar/Navbar";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<SessionContext>
			<html lang="en">
				<body className={inter.className}>
					<NextTopLoader />
					<Navbar />
					<div className="mx-auto max-w-screen-lg h-[89vh] flex flex-col">
						{children}
					</div>
				</body>
			</html>
		</SessionContext>
	);
}
